# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /blog/:title/
# Setup
title:            Oded Welgreen
tagline:          'A Jekyll theme'
description:      'Full stack developer, musician and gamer.'
url:              http://www.odedwelgreen.com

author:
  name:           'Oded Welgreen'
  url:            https://twitter.com/InjaGames

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon

#paths
exclude: [node_modules, styles, scripts, gulpfile.js, package.json]
